### ISSUE TITLE
[Node-webkit] Source ts from web with callback of javascript Uint8Array

### ISSUE THREAD

**Issue by ghost** [RReverser/mpegts#27] opened 2015-08-27 03:30 UTC
I working in node-webkit so I have access to DOM and Node.js. 

I want to be able to get ts chunks from website then covert to mp4 and output the data as a Uint8Array to use with the new MediaSource API

example of what it would look like

```

var ms = new MediaSource();

var video = document.getElementById('stream')
video.src = window.URL.createObjectURL(ms);

ms.addEventListener('sourceopen', function(e) {

    sourceBuffer = ms.addSourceBuffer(['video/mp4; codecs="avc1.42E01E,mp4a.40.2"']);

    mpegts_to_mp4('http://example.com/src.ts',  function (err, array) {
        sourceBuffer.appendBuffer(array); //must be Uint8Array
    });

}, false);
```

**Comment by RReverser** [comment] 2015-08-27 11:03
Duplicate of #20 (and #17). Please look through the issues before opening new one.

**Closed as completed by RReverser** 2015-08-27 11:03 UTC
Labels: duplicate
